In [51]:
import numpy as np
from randomized_hill_climbing import rhc
from utility import build_space

def fitness_func(x):
    cnt = 0
    curr = x[0]
    for i, char in enumerate(x):
        if i==0: continue
        if char != curr:
            cnt += 1
            curr = char
    return cnt

In [49]:
step = 1
lower = 0
upper = 1048575 # binary for this is '11111111111111111111', 20 bits

space = [bin(x)[2:].zfill(20) for x in np.arange(lower, upper, step)]

In [52]:

result = rhc(max_iter=100, fitness_func=fitness_func, space=space, step=1)

randomized search: 1|100


UnboundLocalError: local variable 'left' referenced before assignment

In [58]:
int('0100100010',2)

290

In [54]:
step = 1
lower = 0
upper = 1023 # binary for this is '11111111111111111111', 20 bits
bits=10

space = [bin(x) for x in np.arange(lower, upper, step)]

In [6]:
import numpy as np
x = np.zeros([5,4])

In [11]:
x[3,3]=1

In [12]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [19]:
x[1,1]=1
x[0,1]=1
y = np.where(x==1)

In [21]:
set(y[1])

{1, 3}

In [22]:
x

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [23]:
x[0,:]

array([0., 1., 0., 0.])

In [24]:
y

(array([0, 1, 3], dtype=int64), array([1, 1, 3], dtype=int64))

In [69]:
def fitness_func(x):
    n = len(x)
    score = 100
    # search queens
    queens = np.where(x==1)

    # check row conflicts
    score -= (len(queens[0]) - len(set(queens[0])))*2
    # check col conflicts
    score -= (len(queens[1]) - len(set(queens[1])))*2
    # check diagnal conflicts
    queens = [[queens[0][i],queens[1][i]] for i in range(len(queens[0]))]
    for pos in queens:
        search_se = [pos[0]+1, pos[1]+1]
        search_nw = [pos[0]-1, pos[1]-1]
        search_sw = [pos[0]+1, pos[1]-1]
        search_ne = [pos[0]-1, pos[1]+1]
        while True:
            print("cal fitness function")
            # southeast
            if not np.all(np.isnan(search_se)):
                if search_se[0] > n-1 or search_se[1] > n-1: 
                    search_se = np.nan
                else:
                    if search_se in queens:
                        score -= 1
                    search_se = [search_se[0]+1, search_se[1]+1]
            # northwest
            if not np.all(np.isnan(search_nw)):
                if search_nw[0] < 0 or search_nw[1] < 0:
                    search_nw = np.nan
                else:
                    if search_nw in queens:
                        score -= 1
                    search_nw = [search_nw[0]-1, search_nw[1]-1]
            # southwest
            if not np.all(np.isnan(search_sw)):
                if search_sw[0] > n-1 or search_sw[1] < 0:
                    search_sw = np.nan
                else:
                    if search_sw in queens:
                        score -= 1
                    search_sw = [search_sw[0]+1, search_sw[1]-1]
            # northeast
            if not np.all(np.isnan(search_ne)):
                if search_ne[0] < 0 or search_ne[1] > n-1:
                    search_ne = np.nan
                else:
                    if search_ne in queens:
                        score -= 1
                    search_ne = [search_ne[0]-1, search_ne[1]+1]
#             print(search_se,search_nw,search_sw,search_ne)
            if np.all(np.isnan(search_se))\
            and np.all(np.isnan(search_nw))\
            and np.all(np.isnan(search_sw))\
            and np.all(np.isnan(search_ne)): break
    return score

In [206]:
fitness_func(x)

98


94

In [74]:
x[0,2]=0
x[2,0]=1

In [192]:
def update_neighbor(x):
    n = len(x)
    pos_change = [-1,1]
    idx = [np.random.choice(pos_change), np.random.choice(pos_change)]

    queens = np.where(x==1)
    print(queens)
    queens = [[queens[0][i],queens[1][i]] for i in range(len(queens[0]))]

    while True:
        r = np.random.randint(0, len(queens))
        row, col = queens[r][0], queens[r][1]
        if row+idx[0]<=n-1 \
            and row+idx[0]>=0 \
            and col+idx[1]<=n-1 \
            and col+idx[1]>=0 \
            and [row+idx[0], col+idx[1]] not in queens:
            queens[r] = [row+idx[0], col+idx[1]]
            break
    chess = np.zeros([n,n])
    for q in queens:
        chess[q[0],q[1]] = 1

    return chess

In [193]:
y = update_neighbor(x)

(array([0, 1, 2, 3, 3], dtype=int64), array([1, 1, 0, 2, 3], dtype=int64))


In [194]:
y

array([[0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [196]:
x = np.zeros([3,3])

In [198]:
x[0,0] = 1
x[1,1] = 1
x[2,0] = 1

In [199]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [200]:
y = update_neighbor(x)

(array([0, 1, 2], dtype=int64), array([0, 1, 0], dtype=int64))


In [201]:
y

array([[1., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [203]:
xx = [1,2,3]
xx.pop(-1)

3

In [208]:
list(range(-2,2))

[-2, -1, 0, 1]

In [220]:
import random

random.randint(0,1)

0

In [224]:
def update_chess(n):
    chess = np.zeros([n,n])
    ipos = []
    for i in range(10000):
        irow, icol = np.random.randint(0,n), np.random.randint(0,n)
        if [irow, icol] not in ipos: ipos.append([irow, icol])
        if len(ipos) == n: break
    for pos in ipos:
        chess[pos[0],pos[1]] = 1
    return chess

update_chess(5)

array([[0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [234]:
np.exp(-2)

0.1353352832366127

In [236]:
xx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [245]:
x = np.zeros((3,3))

In [261]:
x[1,2]=12
x[2,1]=77
x[0,0]=121

In [262]:
x

array([[121.,   0.,   0.],
       [  0.,   0.,  12.],
       [  0.,  77.,   0.]])

In [253]:
y = np.copy(x)
y[2,2] = 999
y[1,0] = 45

In [257]:
x

array([[ 0.,  0.,  0.],
       [ 0.,  0., 12.],
       [ 0., 77.,  0.]])

In [265]:
y

array([[  0.,   0.,   0.],
       [ 45.,   0.,  12.],
       [  0.,  77., 999.]])

In [263]:
def mate_queen(parent1, parent2):
    child1 = np.concatenate((parent1[:int(len(parent1)/2)], parent2[int(len(parent2)/2):]), axis=0)
    child2 = np.concatenate((parent2[:int(len(parent2)/2)], parent1[int(len(parent1)/2):]), axis=0)
    return child1, child2

newx, newy = mate_queen(x, y)

In [266]:
newy

array([[ 0.,  0.,  0.],
       [ 0.,  0., 12.],
       [ 0., 77.,  0.]])

In [269]:
xx = np.array([x,y])

In [274]:
x

array([[121.,   0.,   0.],
       [  0.,   0.,  12.],
       [  0.,  77.,   0.]])

In [275]:
np.append(xx, np.array([x]), axis=0)

array([[[121.,   0.,   0.],
        [  0.,   0.,  12.],
        [  0.,  77.,   0.]],

       [[  0.,   0.,   0.],
        [ 45.,   0.,  12.],
        [  0.,  77., 999.]],

       [[121.,   0.,   0.],
        [  0.,   0.,  12.],
        [  0.,  77.,   0.]]])

In [276]:
xx

array([[[121.,   0.,   0.],
        [  0.,   0.,  12.],
        [  0.,  77.,   0.]],

       [[  0.,   0.,   0.],
        [ 45.,   0.,  12.],
        [  0.,  77., 999.]]])

In [279]:
import random
random.__version__

AttributeError: module 'random' has no attribute '__version__'

In [280]:
import mlrose
mlrose.__version__

AttributeError: module 'mlrose' has no attribute '__version__'